### ISSUE TITLE
Clarification on smart contracting

### ISSUE THREAD

**Issue by antoninadert** [UltraDark/UltraDark#15]
What is the plan regarding smart contracting ? Do you plan to support Solidity ?

**Comment by alexdovzhanyn** [comment]
We're still largely unsure of how we want to implement smart contracting at this moment, as the project is still early in development, but I think one option would be to use an existing contracting language (i.e. solidity) to lighten the lpad of the overall implementation. One drawback of solidity though is that its very hard to refer to data that is off-chain , which is something that I think should be possible (although there are some caveats to this), which presents a good case for building one from scratch

**Comment by antoninadert** [comment]
I believe you will have better time using something popular like solidity, rather than trying to micro optimize for something (especially since Oracles are made for this and they will come anyway)

If you go your own path you're going to have a hard time I believe and it will not help adoption

**Comment by alexdovzhanyn** [comment]
That's a good argument. I was thinking of the possibility of using the V8 javascript engine to allow javascript to be written on the chain, which gives the best of both worlds, where we're using an existing language, but one that is already widely adopted. This also means we're able to implement oracle-like behavior within the chain (without them really having to be an oracle) since often times within an application or contract, being able to recreate the exact state of a contract isn't necessary (or rather, basing the state on the external data). 

I think there is a balance to be found with allowing external requests from a dapp, and I feel like the oracle solution doesn't quite fit and is pretty restrictive in terms of what can be done, so maybe having some sort of custom, or at least modified, implementation would be best

**Comment by alexdovzhanyn** [comment]
Closing this issue as per #17, research is currently being done on this.
